providers = ["php", "node"]

[phases.setup]
nixPkgs = [
  "php82",
  "php82Packages.composer",
  "nodejs_20"
]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",

  "npm install",
  "npm run build",

  "php artisan key:generate --force"
]

[start]
cmd = """
php artisan migrate --force || echo 'Migration skipped, table exists' && \
php artisan config:clear && \
php artisan route:clear && \
php artisan serve --host=0.0.0.0 --port=$PORT
"""
