# nixpacks.toml
providers = ["php", "node"]

[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.pdo_mysql",
  "php82Extensions.mbstring",
  "php82Extensions.openssl",
  "php82Extensions.bcmath",
  "php82Extensions.curl",
  "php82Extensions.tokenizer",
  "php82Extensions.xml",
  "php82Extensions.fileinfo",
  "nodejs_20"
]

[phases.install]
cmds = [
  "composer install --no-dev --no-scripts --optimize-autoloader",
  "npm ci"
]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm run build",
  "php artisan optimize"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
